### ISSUE TITLE
Typescript prop errors

### ISSUE THREAD

**Issue by kyh** [MathiasGilson/Tailwind-Styled-Component#29]
Running into some type issues but a basic button that has props passed through
<img width="1041" alt="Button_tsx_—_template" src="https://user-images.githubusercontent.com/4271679/132079644-bb79bfa4-5ca1-4ded-a7e1-ebcc0ea8587a.png">

I'm using the default next.js typescript configuration

```
{
  "compilerOptions": {
    "baseUrl": "src",
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

**Comment by kyh** [comment]
Using `type` instead of an `interface` works

**Comment by MathiasGilson** [comment]
Weird, it works for me, I'm on typescript 4.3.5

**Comment by kyh** [comment]
ill close this issue since there's a clear workaround and until we find a reproducible environment there's nothing we can do here

**Comment by frivolta** [comment]
Same, just cra, styled components, tailwind styled components. 
https://github.com/frivolta/audiophile-fe-client
Note that I have just copied/pasted the examples and the error is reproducible 100% of the times.

**Comment by frivolta** [comment]
Digging: 
i found that tailwind.d.ts as this type:

```
declare type TransientProps = Record<`$${string}`, any>;
```
this is the compatibility issue as if I remove a $ it works:
```
declare type TransientProps = Record<`${string}`, any>;
```

Don't really know how to fix it in tailwind-styled-components.

**Comment by good-idea** [comment]
This appears to be an issue with newer versions of Typescript (4.5+) - I'm not seeing this error on 4.3.2. TS 4.5 has a new feature, "[Template String Types as Discriminants](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#template-string-discriminants)", so it's now parsing this:

```
declare type TransientProps = Record<`$${string}`, any>;
```

In a smarter way. Unfortunately, for those of us using interfaces, those aren't working because **interfaces cannot extend records with templated keys**. Immediate solutions are:

- convert your props interfaces to types
- extend your interfaces with `TransientProps`

Solutions for the lib:

- Update the definition of `TransientProps` to: 
   ```
   declare type TransientProps = Record<`$${string}` | string, any>;
   ```
   (adding that `| string` to the key)
- Or, just remove the TransientProps definition completely:
  - From a type-checking point of view, does this achieve anything special?
