### ISSUE TITLE
 Received `true` for a non-boolean attribute `block`

### ISSUE THREAD

**Issue by sethstha** [MathiasGilson/Tailwind-Styled-Component#6]
It seems like props are passed as an attribute and when I pass boolean, It throws error on the console. I am using next.js with typescript.

This is the error
```
Warning: Received `true` for a non-boolean attribute `block`.

If you want to write it to the DOM, pass a string instead: block="true" or block={value.toString()}.
button
functionTemplate/</<@webpack-internal:///./node_modules/tailwind-styled-components/dist/tailwind.js:34:101
```

Component looks like this
```
import tw from 'tailwind-styled-components';

interface Props {
  layout?: 'primary' | 'outline';
  disabled?: boolean;
  block?: boolean;
  size?: 'small' | 'medium' | 'large';
}

const Button = tw.button`
  flex justify-center items-center border border-solid font-medium rounded-sm transition-all duration-300 ease-in-out

  ${(props: Props) =>
    props.layout === 'primary' &&
    'border-primary-400 bg-primary-400 text-white hover:bg-primary-500 hover:border-primary-600'}
  ${(props: Props) =>
    props.layout === 'outline' &&
    'border-gray-300 text-gray-700 hover:border-blue-500 hover:text-blue-500'}

  ${(props: Props) =>
    props.disabled && 'bg-gray-50 border-gray-200 text-gray-200'}
    
  ${(props: Props) => props.size === 'small' && 'px-2 py-2 text-xs'}
  ${(props: Props) => props.size === 'medium' && 'px-4 py-3 text-xs'}
  ${(props: Props) => props.size === 'large' && 'px-5 py-4 text-lg'}
  
  ${(props: Props) => props.block && 'w-full'}
`;

export default Button;
```

The workaround is using number as boolean `block ? 1 : 0`

**Comment by MathiasGilson** [comment]
Hello,

Yes I have the same issue, apparently Styled component has it as well.
The only clean solution would be to sanitize the property based on the tag.
So your button would get the prop "block" removed as it's not a default HTML prop.
But that would require to ship the list of all the HTML props of every tags in the package and I need to make sure that this will not end up in production or it will add a lot of useless code to the prod bundle.

If you find someone who implemented a clean solution let me know 😉 
Otherwise using number instead of boolean is a good quick fix.

**Comment by cemreinanc** [comment]
Hello,

I think styled-components have a solution called transient props: https://styled-components.com/docs/api#transient-props

I tried a similar one with a quick one liner: 
https://github.com/cemreinanc/Tailwind-Styled-Component/commit/abb453f4acb2b3620526855c7b894d341c82cc09

this method just filters out the props that starts with "$" from the dom element but they are still usable in styles.
Would you consider implementing something like this? @MathiasGilson

**Comment by m50** [comment]
```ts
const appliedProps = {...props}
if (intrinsicElements.includes(Element)) {
  appliedProps = appliedProps.filter(p => typeof p === 'string');
}
```

This is an idea?

Though, if my PR (#8) is merged, that would no longer work. 🤔 

Alternatively, a change in PR could be requiring the keys of the transient props start with `$`, and do as @cemreinanc said and filter those out when spreading into the Element.

**Comment by MathiasGilson** [comment]
Hello @m50,

I'm reviewing your PR.
Impressive work!
Thank you very much for taking the time to improve and type the code 😄 

I wonder if there would be a way to filter the props out at the compilation time versus runtime.
So that we can simply have file with all the props accepted by the browser for each html element and filter the props out while compiling the bundle.
I think that this would require a webpack extension too though 😬

What do you think ?

**Comment by m50** [comment]
Personally, I picked this over twin because there is no webpack extension required. If it required a webpack extension, I'd have to stop using this, as I use Snowpack, and I have no interest in using Webpack with it.

There is [a package](https://www.npmjs.com/package/react-dom-props) which just lists them out, but this is a slight worry to use, just cause you would need very different functionality between standard elements and custom components. But this is, again, at runtime, not compilation time.

Now, if that extra overhead is wanted, then it's a perfectly fine way to go. 

But another, simpler, and just as effective solution is to go with what was mentioned before, and have transient props exist with specific keys, and be filtered out before applying them, as mentioned already.

**Comment by MathiasGilson** [comment]
Got you, I'll implement the Transient props then 😉

**Comment by MathiasGilson** [comment]
<img width="622" alt="Screenshot 2021-04-27 at 19 12 21" src="https://user-images.githubusercontent.com/7348817/116291451-7ed3c580-a78c-11eb-881e-262b018aaafe.png">

I can't inforce the $ as the first character of the props though, any idea ?

**Comment by cemreinanc** [comment]
I think you can't enforce that but also probably you shouldn't?
Because if we want to still pass a prop to underlying dom element we should be able to write that without the $ sign.

**Comment by m50** [comment]
Weird that it doesn't recognize a template literal as a string. I am not sure on that one. I haven't had issues like that in the past. Maybe it's because I usually use a slightly newer TS? Dunno.

@cemreinanc: you make a good point though, but then it has the caveat that they can't be booleans, and can't have any capitals in the key. Not sure that's completely ideal.

And FWIW, the typing for the TransientProps is only for what you pass in like this:

```tsx
const MyDiv = tw.div<{ $primary: true }>`${p => p.primary ? 'bg-gray-400' : 'bg-black'`;
```

It doesn't prevent you from passing things like `data-something="something"` to it when using it.

```tsx
<MyDiv $primary={isPrimary} data-something="something">Hi</MyDiv>
```

It only is for props that are meant to be used *only* within the styles. All other props are based on the original components props.

Adding the `$` requirement just stops you from this:

```tsx
const MyDiv = tw.div<{ primary: true }>`${p => p.primary ? 'bg-gray-400' : 'bg-black'`;
<MyDiv primary={isPrimary} data-something="something">Hi</MyDiv> // Error because booleans can't be sent to the dom
```

**Comment by m50** [comment]
Ahhhh @MathiasGilson : I think you need at least TS4.1, TS4.0 (which is currently in use) doesn't support template literal types.

**Comment by MathiasGilson** [comment]
Good catch but it still doesn't work after the update.
The Template Literal Types work now but not as index signature parameter type.

<img width="604" alt="Screenshot 2021-04-27 at 19 47 16" src="https://user-images.githubusercontent.com/7348817/116295795-6023fd80-a791-11eb-9a31-2d05a4ca131f.png">

**Comment by MathiasGilson** [comment]
<img width="929" alt="Screenshot 2021-04-27 at 19 48 07" src="https://user-images.githubusercontent.com/7348817/116295894-7f228f80-a791-11eb-8a11-4e9f943ccc19.png">

I got an issue with the typing when trying to filter the props out too 😭 
You seem to be way better than me at typing, if you have the time to PR it would be greatly appreciated!

**Comment by m50** [comment]
`{...Object.........) as P}`

Need to specify the type here, because it can't be certain.

As for the template literal keys, I'll have to take a look after work today to see if I have a solution for you. I could have sworn it would work.

You could try: `type TransientProps = Record<`$${string}`, any>`, maybe using a Record would work? Records are technically just objects as well.

**Comment by MathiasGilson** [comment]
Wow nice it worked! Well done 👍 

The only catch is that it doesn't seem to enforce the $ at the start of the props

<img width="453" alt="Screenshot 2021-04-27 at 20 03 41" src="https://user-images.githubusercontent.com/7348817/116297883-ac703d00-a793-11eb-85c4-27e2dd7bc270.png">

**Comment by m50** [comment]
Yeah, tried that. 🤔 

![image](https://user-images.githubusercontent.com/3577147/116298140-b1b49400-a761-11eb-8747-06f30dc71c44.png)

https://stackoverflow.com/questions/65878880/typescript-template-literal-as-interface-key

According to jcalz there, we might be able to do it in TS4.4, but until then, looks like the template literal keys won't work.

Maybe his solution of a function might work, but I don't think so.

Oh well, can't enforce it with types, but I suppose documenting it should work. 🤷‍♀️

**Comment by MathiasGilson** [comment]
Yeah I read the same stack overflow.

Perfect then we will implement it once typescript 4.4 is out.

I'll just document it for now.

Thank you so much for your help 🙏

**Comment by m50** [comment]
Happy to help. :)

**Comment by MathiasGilson** [comment]
New NPM package release with transient props support and way better typing.
Many thanks to @m50 and @cemreinanc for your help!
